const BASE = "./assets/masks/";

export const maskPresets = {
  location: `${BASE}Location.png`,
  "dollar-sign": `${BASE}Dollar-sign.png`,
  microphone: `${BASE}Microphone.png`,
  file: `${BASE}File.png`,
  keyhole: `${BASE}Keyhole.png`,
  toolkit: `${BASE}Toolkit.png`,
  "shop-2": `${BASE}Shop-2.png`,
  phone: `${BASE}Phone.png`,
  trophy: `${BASE}Trophy.png`,

  "house-fence": `${BASE}House-fence.png`,
  candle: `${BASE}Candle.png`,
  "t-shirts": `${BASE}T-shirts.png`,
  hammer: `${BASE}Hammer.png`,
  shop: `${BASE}Shop.png`,
  info: `${BASE}Info.png`,
  camera: `${BASE}Camera.png`,
  balloon: `${BASE}Balloon.png`,
  "credit-card-hand": `${BASE}Credit-card-hand.png`,

  "martini-glass": `${BASE}Martini-glass.png`,
  "pizza-slice": `${BASE}Pizza-slice.png`,
  door: `${BASE}Door.png`,
  mug: `${BASE}mug.png`,
  "wine-glass": `${BASE}Wine-glass.png`,
  fish: `${BASE}Fish.png`,
  "house-2": `${BASE}House-2.png`,
  "food-platter": `${BASE}Food-platter.png`,
  lobster: `${BASE}Lobster.png`,

  key: `${BASE}Key.png`,
  "tip-jar": `${BASE}Tip-jar.png`,
  wallet: `${BASE}Wallet.png`,
  ticket: `${BASE}Ticket.png`,
  calendar: `${BASE}Calendar.png`,
  cloud: `${BASE}Cloud.png`,
  lock: `${BASE}Lock.png`,
  gift: `${BASE}Gift.png`,
  profile: `${BASE}Profile.png`,

  heart: `${BASE}Heart.png`,
  "play-button": `${BASE}Play-button.png`,
  megaphone: `${BASE}Megaphone.png`,
  "repair-wrench": `${BASE}Repair-Wrench.png`,
  pharmacy: `${BASE}Pharmacy.png`,
  "human-head": `${BASE}Human-head.png`,
  "question-mark": `${BASE}Question-mark.png`
};
