const BASE = "./assets/masks/";

export const maskPresets = {
  location: `${BASE}Location.png.PNG`,
  "dollar-sign": `${BASE}Dollar-sign.PNG`,
  microphone: `${BASE}Microphone.PNG`,
  file: `${BASE}File.PNG`,
  keyhole: `${BASE}Keyhole.PNG`,
  toolkit: `${BASE}Toolkit.PNG`,
  "shop-2": `${BASE}Shop-2.PNG`,
  phone: `${BASE}Phone. PNG`,
  trophy: `${BASE}Trophy.PNG`,

  "house-fence": `${BASE}House-fence.PNG`,
  candle: `${BASE}Candle.PNG`,
  "t-shirts": `${BASE}T-shirts.PNG`,
  hammer: `${BASE}Hammer.PNG`,
  shop: `${BASE}Shop.PNG`,
  info: `${BASE}Info.PNG`,
  camera: `${BASE}Camera PNG`,
  balloon: `${BASE}Balloon.PNG`,
  "credit-card-hand": `${BASE}Credit-card-hand.PNG`,

  "martini-glass": `${BASE}Martini-glass.PNG`,
  "pizza-slice": `${BASE}Pizza-slice.PNG`,
  door: `${BASE}Door.PNG`,
  mug: `${BASE}mug.PNG`,
  "wine-glass": `${BASE}Wine-glass.PNG`,
  fish: `${BASE}Fish.png.PNG`,
  "house-2": `${BASE}House-2.PNG`,
  "food-platter": `${BASE}Food-platter.PNG`,
  lobster: `${BASE}Lobster.PNG`,

  key: `${BASE}Key.PNG`,
  "tip-jar": `${BASE}Tip-jar.PNG`,
  wallet: `${BASE}Wallet.PNG`,
  ticket: `${BASE}Ticket.PNG`,
  calendar: `${BASE}Calendar.PNG`,
  cloud: `${BASE}Cloud.PNG`,
  lock: `${BASE}Lock.PNG`,
  gift: `${BASE}Gift.PNG`,
  profile: `${BASE}Profile. PNG`,

  heart: `${BASE}Heart.PNG`,
  "play-button": `${BASE}Play-button.PNG`,
  megaphone: `${BASE}Megaphone.PNG`,
  "repair-wrench": `${BASE}Repair-Wrench.PNG`,
  pharmacy: `${BASE}Pharmacy.PNG`,
  "human-head": `${BASE}Human-head.PNG`,

  house: `${BASE}house.png`,
  star: `${BASE}star.png`,
  tree: `${BASE}tree.png`,
  turtle: `${BASE}turtle.png`
};
